# Generated by Django 5.0.6 on 2024-07-09 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_departamento_remove_telefone_cliente_empregado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empregado',
            name='departamentos',
        ),
    ]
