# Generated by Django 5.0.7 on 2024-07-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_empregado_departamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empregado',
            old_name='Salario',
            new_name='salario',
        ),
        migrations.AddField(
            model_name='empregado',
            name='foto',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
